---

- name: Setup variables
  ansible.builtin.import_tasks:
    file: vars.yml
  tags:
    - system
    - cron
    - vars
    - cron-vars

- name: Install cron
  ansible.builtin.import_tasks:
    file: install.yml
  tags:
    - system
    - cron
    - install
    - cron-install

- name: Configure cron jobs
  ansible.builtin.import_tasks:
    file: config.yml
  tags:
    - system
    - cron
    - config
    - cron-config

- name: Configure cron service
  ansible.builtin.import_tasks:
    file: service.yml
  tags:
    - system
    - cron
    - service
    - cron-service
